[package]
name = "cable_handshake"
version = "0.1.0"
authors = ["glyph <glyph@mycelial.technology>"]
description = "Cable handshake protocol implementation"
edition = "2021"

[dependencies]
desert = { path = "../desert" }
log = "0.4.20"
snow = "0.9.4"
